name: Generate and Use Output

on:
  push:
    branches:
      - master

jobs:
  generate-output:
    name: Generate Output
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Generate Output
        id: generate-output
        run: |
          # Run your Node.js script here to generate the output
          output=$(node generateOutput.js)
          echo "::set-output name=output::$output"
          - name: Set output using new method 
          run: echo "{name}={value}" >> $GITHUB_OUTPUT

  use-output:
    name: Use Generated Output
    needs: generate-output
    runs-on: ubuntu-latest

    steps:
      - name: Print Generated Output
        run: |
          # Access the generated output using the `steps` context and the `output` identifier
          echo "Generated output: ${{ steps.generate-output.outputs.output }}"
