name: Mediator Workflow

on:
  push:
    branches:
      - master1
      
jobs:
  generate-and-print:  # Define the job name
    runs-on: ubuntu-latest  # Specify the runner

    steps:
      - uses: actions/checkout@v3

      - name: Generate Random Numbers
        uses: ./mediator.yml@v1  # Call mediator workflow
        inputs:
          script: ./generate-numbers.js  # Path to Node.js script
          message: "Generated random numbers:"  # Optional message

      - name: Print Generated Numbers
        run: |
          echo ${{ steps.generate_numbers.outputs.message }}
          echo ${{ steps.generate_numbers.outputs.numbers }}
