name: Mediator Workflow

on:
  push:
    branches:
      - master1
      
inputs:
  script: required  # Path to the Node.js script
  message: optional  # Optional message to include in the output

runs-on: ubuntu-latest

steps:
  - uses: actions/checkout@v3

  - name: Run Node.js Script
    run: |
      npm install  # Install dependencies (if any)
      node ${{ inputs.script }}

  - name: Capture Output
    run: |
      numbers=$(cat output.txt)  # Assuming output is written to a file
      echo "::set-output name=message::${{ inputs.message }}"
      echo "::set-output name=numbers::$numbers"

  - name: Print Mediator Output (Optional)
    run: |
      echo "Mediator Message: ${{ steps.capture_output.outputs.message }}"
      echo "Mediator Numbers: ${{ steps.capture_output.outputs.numbers }}"
